name: uni_fit
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth:
  firebase_core:
  cloud_firestore:
  firebase_database:
  google_sign_in:
  font_awesome_flutter: ^9.1.0
  tflite: ^1.1.1
  camera: ^0.5.8+11
  page_transition: ^1.1.7+6
  confetti:
  carousel_slider:
  google_maps_flutter: ^2.0.2
  geolocator:
  flutter_polyline_points: ^0.2.6
  dio: ^4.0.0
  location:
  url_launcher:
  new_version:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  flutter_native_splash: ^2.0.1+1

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_screen_logo.png
  branding: assets/images/branding.png
  branding_mode: bottom
  android: true
  ios: true

  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/posenet_mv1_075_float_from_checkpoints.tflite
    - assets/images/logo.png
    - assets/images/
    - assets/images/diet/
    - assets/exercises/
    - assets/images/advance/
    - assets/images/beginner/
    - assets/images/intermediate/
    - assets/images/gif/

  fonts:
    - family: popBold
      fonts:
        - asset: assets/font/poppins_bold.otf

    - family: popLight
      fonts:
        - asset: assets/font/poppins_light.otf

    - family: popMedium
      fonts:
        - asset: assets/font/poppins_medium.otf
